# Generated by Django 4.1.6 on 2023-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misPeliculas', '0002_rename_directorio_pelicula_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='descargada',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
